resources:
  repositories:
    - repository: templates
      type: github
      endpoint: github
      name: ccdc-opensource/conan-azure-devops
      ref: refs/heads/development

extends:
  template: third-party-library-all-platforms-from-conan-center.yml@templates
  parameters:
    package: zstd
    package_version: 1.5.5
    source_repository: public-conan-center
    destination_repository: ccdc-3rdparty-conan
